from: markdown+gfm_auto_identifiers+hard_line_breaks+lists_without_preceding_blankline
to: pdf
pdf-engine: lualatex

metadata:
  title: "Stories from 2025"
  author: "ANDREI - IOAN CIOARA"

# A5 size is 148x210 mm
# Bleed is defined as 0.125 in (3.18 mm) on each edge (6.36 mm added to each length)
# https://help.lulu.com/en/support/solutions/articles/64000255584-what-is-full-bleed-
#
# Fonts are discussed in
# https://chatgpt.com/share/68ed6cef-d4e0-8005-a8cd-170b36ac0f91
variables:
  documentclass: book
  geometry:
    - inner=18mm        # choose preset values
    - outer=18mm
    - top=18mm
    - bottom=25mm
    # - papersize={154.36mm,216.36mm} # A5 + 2 * 3.18mm bleed
    # - layoutwidth=148mm             # Actual A5 width
    # - layoutheight=210mm            # Actual A5 height
    # - layoutoffset={3.18mm,3.18mm}  # Center
    # - showcrop                      # shows crop marks at trim edges
    - papersize={148mm,210mm}
  fontsize: 10pt


# Ensure each chapter starts on a new page
top-level-division: chapter

toc: true
toc-depth: 1

# Allows attachments
resource-path:
  - /content
  - .
